export type SupportedLanguage = 'ko' | 'en' | 'zh' | 'ja' | 'pl' | 'de-CH';

export interface LanguageOption {
  code: SupportedLanguage;
  label: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'ko', label: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'en', label: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'zh', label: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ja', label: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'pl', label: 'Polish', nativeName: 'Polski', flag: '🇵🇱' },
  { code: 'de-CH', label: 'Swiss German', nativeName: 'Schwiizertüütsch', flag: '🇨🇭' },
];

export const DEFAULT_LANGUAGE: SupportedLanguage = 'ko';

export const SITE_CONFIG = {
  title: 'Eunseong Park | Researcher @ Virginia Tech',
  name: 'Eunseong Park',
  koreanName: '박은성',
  role: 'Graduate Researcher / Ph.D. Student',
  affiliation: 'Virginia Tech (Department of Computer Science / ECE)',
  description: 'Researching Neural BCI (Biomimetic RAS), Confidential GPU LLM Serving, and Trustworthy AI Systems at Virginia Tech.',
  url: 'https://esp-vt.github.io',
  author: 'Eunseong Park',
  email: 'esp@vt.edu',
  phone: '(540) 824-9625',
  cvUrl: 'https://drive.google.com/file/d/10enuA74dQgLyE-eyf2KXTBKaxk1xdvtX/view?usp=sharing',
  social: {
    github: 'https://github.com/esp-vt',
    linkedin: 'https://linkedin.com',
    scholar: 'https://scholar.google.com/citations?user=4wkSQnMAAAAJ&hl=en',
    twitter: 'https://x.com',
  },
  giscus: {
    repo: 'esp-vt/esp-vt.github.io',
    repoId: 'YOUR_REPO_ID',
    category: 'Announcements',
    categoryId: 'YOUR_CATEGORY_ID',
    mapping: 'pathname',
    reactionsEnabled: '1',
    theme: 'preferred_color_scheme',
  },
};

export const UI_TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  ko: {
    // Nav
    'nav.home': '홈',
    'nav.projects': '연구 & 프로젝트',
    'nav.blog': '기술 블로그',
    'nav.about': '소개',
    'nav.search': '검색',

    // Hero
    'hero.greeting': '안녕하세요,',
    'hero.badge': 'Virginia Tech Graduate Researcher',
    'hero.role': 'Virginia Tech 컴퓨터공학 / ECE 대학원 연구원 (Ph.D. Student)',
    'hero.desc': '생체모방 망상활성계(RAS) 기반 뇌파 BCI 텔레파시, 기밀 GPU 기반 거대 언어 모델(LLM) 서빙 성능 프로파일링 및 신뢰 가능한 AI 시스템을 연구합니다.',
    'hero.contact': '이메일',
    'hero.resume': '이력서 (CV)',

    // Section Titles
    'section.featured_projects': '주요 연구 & 프로젝트',
    'section.featured_projects_desc': '뇌파 BCI 및 기밀 GPU(NVIDIA H100 CC) 기반 LLM 서빙 핵심 연구입니다.',
    'section.recent_posts': '기술 블로그 포스팅',
    'section.recent_posts_desc': '생체 신호처리, BCI, 기밀 컴퓨팅 시스템에 관한 기술적 기록입니다.',
    'section.tech_stack': '기술 스택',
    'section.timeline': '학력 & 연구 이력',
    'section.all_projects': '전체 프로젝트 →',
    'section.all_posts': '전체 글 보기 →',

    // Projects Cards Translation
    'proj.telepathy.title': 'Telepathy: 생체모방 RAS 기반 크로스-링구얼 뇌파 BCI',
    'proj.telepathy.desc': '8채널 비침습 EEG에서 언어 장벽 없는 순수 개념 및 감정을 2.72ms로 해독하여 8개 언어로 직접 전송 (연산량 99.7% 절감).',
    'proj.telepathy.cat': 'Research',
    'proj.ispass.title': 'An Empirical Study of LLM Serving in Confidential GPUs (ISPASS 2026 🏆)',
    'proj.ispass.desc': 'ISPASS 2026 Best Paper Honorable Mention: NVIDIA H100 TEE 환경에서 vLLM, SGLang 거대 언어 모델 서빙의 하드웨어 암호화 오버헤드, Chunked Prefill, PagedAttention 및 Speculative Decoding 실측 분석.',
    'proj.ispass.cat': 'Research',

    // Blog Cards Translation
    'post.ras.title': '생체모방 망상활성계(RAS) 바이오 신호 필터링: BCI 연산 99.7% 절감과 인지 가속의 원리',
    'post.ras.desc': '뇌간의 망상활성계(RAS) 메커니즘을 모방하여 유휴 뇌파를 차단하고 속발음 의도만을 2.72ms로 해독하는 신호처리 아키텍처 완전 해부.',
    'post.prov.title': '데이터 프로비넌스(Data Provenance)의 기초와 신뢰 가능한 AI 시스템 구축',
    'post.prov.desc': 'AI 학습 데이터셋의 생성, 정제, 변형 전 과정을 암호학적으로 추적하고 검증하는 데이터 프로비넌스 아키텍처를 소개합니다.',
    'post.tee.title': '기밀 컴퓨팅(Confidential Computing)과 TEE 핵심 아키텍처 완전 가이드',
    'post.tee.desc': 'Intel SGX, AMD SEV-SNP, ARM CCA의 아키텍처 비교 및 클라우드 환경에서의 메모리 암호화와 원격 증명 원리.',
    'post.astro.title': 'Astro와 GitHub Pages로 비용 0원 초고속 개발자 포트폴리오 & 블로그 만들기',
    'post.astro.desc': 'Astro Content Collections, 6개 국어 i18n, 다크/라이트 모드, GitHub Actions CI/CD 자동 배포 구축기.',

    // Tech Stacks
    'stack.bci': '뇌파 BCI & 생체 신경 신호처리',
    'stack.tee': '기밀 하드웨어 & TEE',
    'stack.ai': '신뢰 가능한 AI & LLM',
    'stack.systems': '시스템 & 클라우드 보안',

    // Timeline
    'timeline.phd_title': 'Ph.D. 과정 & 대학원 연구원',
    'timeline.phd_org': 'Virginia Tech (CS / ECE)',
    'timeline.phd_desc': '생체모방 망상활성계(RAS) 크로스-링구얼 뇌파 BCI 텔레파시, 기밀 GPU (NVIDIA H100 CC) 기반 거대 언어 모델 서빙 성능 프로파일링 및 최적화 연구.',
    'timeline.bs_title': '컴퓨터공학 학사 (B.S.)',
    'timeline.bs_org': '컴퓨터공학과 학부 과정',
    'timeline.bs_desc': '생체 신호처리, 운영체제(OS), 컴퓨터 구조, 암호학, 분산 시스템, 네트워크 보안 및 딥러닝 알고리즘 이수.',

    // Projects Page Filters & Labels
    'projects.filter_all': '전체',
    'projects.filter_research': 'Research',
    'projects.filter_ai': 'AI & ML',
    'projects.filter_security': 'Security',
    'projects.filter_fullstack': 'Fullstack',
    'projects.live_demo': '데모',
    'projects.source_code': 'GitHub',
    'projects.paper': '논문 / Citation',
    'projects.slides': '발표 슬라이드',

    // Blog & Post Meta
    'blog.filter_all': '전체 보기',
    'post.reading_time': '분 소요',
    'post.published': '작성일:',
    'post.toc': '목차',
    'post.back': '← 목록으로 돌아가기',
    'post.comments': '댓글',
    'post.tags': '태그',
    'post.share': '공유하기',
    'post.translate_notice': '🌐 언어별 실시간 번역 열람:',
    'post.copy_link': '🔗 링크 복사',
    'post.copied': '✓ 복사 완료!',

    // Search Page
    'search.page_title': '통합 검색',
    'search.page_desc': '논문, 프로젝트, 기술 스택을 실시간으로 검색합니다.',
    'search.placeholder': '검색어 입력... (Ctrl+K)',
    'search.no_results': '검색 결과가 없습니다.',
    'search.count_prefix': '총 ',
    'search.count_suffix': '개의 결과',

    // Footer
    'footer.rights': 'All rights reserved.',
    'footer.built_with': 'Built with Astro & GitHub Pages',
  },

  en: {
    // Nav
    'nav.home': 'Home',
    'nav.projects': 'Research & Projects',
    'nav.blog': 'Tech Blog',
    'nav.about': 'About',
    'nav.search': 'Search',

    // Hero
    'hero.greeting': 'Hello, I am',
    'hero.badge': 'Virginia Tech Graduate Researcher',
    'hero.role': 'Graduate Researcher / Ph.D. Student @ Virginia Tech (CS / ECE)',
    'hero.desc': 'Researching Biomimetic RAS Neural BCI Telepathy, Confidential GPU LLM Serving Performance Profiling, and Trustworthy AI Systems at Virginia Tech.',
    'hero.contact': 'Email',
    'hero.resume': 'Resume (CV)',

    // Section Titles
    'section.featured_projects': 'Featured Research & Projects',
    'section.featured_projects_desc': 'Core research on Neural BCI and Confidential GPU (NVIDIA H100 CC) LLM Serving.',
    'section.recent_posts': 'Technical Blog Articles',
    'section.recent_posts_desc': 'Deep-dives into bio-signal processing, BCI architectures, and systems benchmarking.',
    'section.tech_stack': 'Tech Stack',
    'section.timeline': 'Education & Experience',
    'section.all_projects': 'All Projects →',
    'section.all_posts': 'All Articles →',

    // Projects Cards Translation
    'proj.telepathy.title': 'Telepathy: Biomimetic RAS Cross-Lingual Neural BCI',
    'proj.telepathy.desc': '8-channel non-invasive EEG decoding language-agnostic concepts and affective states in 2.72ms with 99.7% compute savings.',
    'proj.telepathy.cat': 'Research',
    'proj.ispass.title': 'An Empirical Study of LLM Serving in Confidential GPUs (ISPASS 2026 🏆)',
    'proj.ispass.desc': 'ISPASS 2026 Best Paper Honorable Mention: Comprehensive performance profiling of vLLM and SGLang under NVIDIA H100 Confidential GPU environments analyzing Chunked Prefill, PagedAttention, and Speculative Decoding.',
    'proj.ispass.cat': 'Research',

    // Blog Cards Translation
    'post.ras.title': 'Biomimetic RAS Bio-Signal Gating: 99.7% Compute Savings in Neural BCI',
    'post.ras.desc': 'Architectural deep-dive into mimicking brainstem Reticular Activating System (RAS) to filter idle EEG and decode inner speech in 2.72ms.',
    'post.prov.title': 'Data Provenance Fundamentals for Trustworthy AI Systems',
    'post.prov.desc': 'Cryptographically tracking and verifying the entire data lifecycle from ingestion to model training.',
    'post.tee.title': 'Confidential Computing and TEE Architecture Guide',
    'post.tee.desc': 'Architectural comparison of Intel SGX, AMD SEV-SNP, ARM CCA and memory encryption principles.',
    'post.astro.title': 'Zero-Cost Fast Developer Portfolio with Astro & GitHub Pages',
    'post.astro.desc': 'Astro Content Collections, 6-language i18n, dark mode, and GitHub Actions CI/CD pipeline.',

    // Tech Stacks
    'stack.bci': 'Neural BCI & Bio-Signal Processing',
    'stack.tee': 'Confidential Hardware & TEE',
    'stack.ai': 'Trustworthy AI & LLM',
    'stack.systems': 'Systems & Cloud Security',

    // Timeline
    'timeline.phd_title': 'Ph.D. Student & Graduate Researcher',
    'timeline.phd_org': 'Virginia Tech (CS / ECE)',
    'timeline.phd_desc': 'Conducting research on biomimetic RAS-gated neural BCI telepathy and performance profiling of LLM serving frameworks in Confidential GPUs (NVIDIA H100 CC).',
    'timeline.bs_title': 'B.S. in Computer Science & Engineering',
    'timeline.bs_org': 'Undergraduate CS Program',
    'timeline.bs_desc': 'Coursework in Signal Processing, Operating Systems, Computer Architecture, Cryptography, Distributed Systems, and Deep Learning.',

    // Projects Page Filters & Labels
    'projects.filter_all': 'All',
    'projects.filter_research': 'Research',
    'projects.filter_ai': 'AI & ML',
    'projects.filter_security': 'Security',
    'projects.filter_fullstack': 'Fullstack',
    'projects.live_demo': 'Demo',
    'projects.source_code': 'GitHub',
    'projects.paper': 'Paper / Citation',
    'projects.slides': 'Slides',

    // Blog & Post Meta
    'blog.filter_all': 'All Posts',
    'post.reading_time': 'min read',
    'post.published': 'Published:',
    'post.toc': 'Table of Contents',
    'post.back': '← Back to List',
    'post.comments': 'Comments',
    'post.tags': 'Tags',
    'post.share': 'Share',
    'post.translate_notice': '🌐 Instant Multi-Language Translation:',
    'post.copy_link': '🔗 Copy Link',
    'post.copied': '✓ Copied!',

    // Search Page
    'search.page_title': 'Global Search',
    'search.page_desc': 'Real-time search across research papers, projects, and topics.',
    'search.placeholder': 'Search topics... (Ctrl+K)',
    'search.no_results': 'No matching results found.',
    'search.count_prefix': 'Found ',
    'search.count_suffix': ' results',

    // Footer
    'footer.rights': 'All rights reserved.',
    'footer.built_with': 'Built with Astro & GitHub Pages',
  },

  zh: {
    'nav.home': '首页',
    'nav.projects': '研究与项目',
    'nav.blog': '技术博客',
    'nav.about': '关于我',
    'nav.search': '搜索',
    'hero.greeting': '你好，我是',
    'hero.badge': '弗吉尼亚理工大学 (Virginia Tech) 研究员',
    'hero.role': '弗吉尼亚理工大学 计算机/ECE 博士生 & 研究员',
    'hero.desc': '专注于生体仿生网状激活系统（RAS）脑机接口（BCI）、机密GPU大语言模型服务性能分析及可信AI系统研究。',
    'hero.contact': '邮箱',
    'hero.resume': '个人简历 (CV)',
    'section.featured_projects': '重点研究与项目',
    'section.featured_projects_desc': '脑电波脑机接口(BCI)与机密GPU (NVIDIA H100 CC) LLM服务评测核心成果。',
    'section.recent_posts': '最新技术文章',
    'section.recent_posts_desc': '关于神经信号处理、BCI架构与系统性能评测的深度记录。',
    'section.tech_stack': '技术栈',
    'section.timeline': '教育与经历',
    'section.all_projects': '查看所有项目 →',
    'section.all_posts': '查看全部文章 →',
    'proj.telepathy.title': 'Telepathy: 生体仿生RAS多语言脑波脑机接口',
    'proj.telepathy.desc': '基于8通道无创EEG解算无语种限制的心语概念与情绪（延迟2.72ms，算力降低99.7%）。',
    'proj.telepathy.cat': 'Research',
    'proj.ispass.title': 'An Empirical Study of LLM Serving in Confidential GPUs (ISPASS 2026 🏆)',
    'proj.ispass.desc': 'ISPASS 2026 Best Paper Honorable Mention: 评测 NVIDIA H100 机密GPU环境下 vLLM 与 SGLang 的硬件加密开销、分块预填充、分页注意力与推测解码性能。',
    'proj.ispass.cat': 'Research',
    'post.ras.title': '生体仿生网状激活系统(RAS)生物信号过滤：BCI算力降低99.7%的原理',
    'post.ras.desc': '模拟脑干网状激活系统(RAS)以过滤闲置脑电波并在2.72ms内解算心语的信号处理架构解析。',
    'post.prov.title': '可信AI系统的数据溯源(Data Provenance)基础',
    'post.prov.desc': '密码学追踪并验证从数据采集到模型训练的全生命周期。',
    'post.tee.title': '机密计算与TEE硬件架构完全指南',
    'post.tee.desc': 'Intel SGX、AMD SEV-SNP、ARM CCA架构对比与内存加密原理。',
    'post.astro.title': '基于 Astro 与 GitHub Pages 零成本搭建极速开发者主页',
    'post.astro.desc': 'Astro Content Collections、6国语言支持与GitHub Actions CI/CD流水线。',
    'stack.bci': '脑机接口(BCI)与神经信号处理',
    'stack.tee': '机密硬件与TEE',
    'stack.ai': '可信AI与大模型',
    'stack.systems': '系统与云安全',
    'timeline.phd_title': '博士研究生 & 大学院研究员',
    'timeline.phd_org': '弗吉尼亚理工大学 (CS / ECE)',
    'timeline.phd_desc': '开展生体仿生RAS多语言脑机接口与机密GPU环境下大模型服务性能分析研究。',
    'timeline.bs_title': '计算机工程学士 (B.S.)',
    'timeline.bs_org': '计算机工程专业',
    'timeline.bs_desc': '完成脑电信号处理、操作系统、计算机体系结构、密码学及深度学习课程。',
    'projects.filter_all': '全部',
    'projects.filter_research': '研究',
    'projects.filter_ai': 'AI / ML',
    'projects.filter_security': '安全',
    'projects.filter_fullstack': '全栈',
    'projects.live_demo': '演示',
    'projects.source_code': 'GitHub',
    'projects.paper': '论文 / Citation',
    'projects.slides': '幻灯片',
    'blog.filter_all': '查看全部',
    'post.reading_time': '分钟阅读',
    'post.published': '发布日期：',
    'post.toc': '目录',
    'post.back': '← 返回列表',
    'post.comments': '评论',
    'post.tags': '标签',
    'post.share': '分享',
    'post.translate_notice': '🌐 实时多语言翻译阅读：',
    'post.copy_link': '🔗 复制链接',
    'post.copied': '✓ 已复制！',
    'search.page_title': '全局检索',
    'search.page_desc': '实时检索论文、项目与技术主题。',
    'search.placeholder': '输入关键词... (Ctrl+K)',
    'search.no_results': '未找到匹配结果。',
    'search.count_prefix': '共检索到 ',
    'search.count_suffix': ' 条结果',
    'footer.rights': '保留所有权利。',
    'footer.built_with': '基于 Astro 与 GitHub Pages 构建',
  },

  ja: {
    'nav.home': 'ホーム',
    'nav.projects': '研究・プロジェクト',
    'nav.blog': '技術ブログ',
    'nav.about': '自己紹介',
    'nav.search': '検索',
    'hero.greeting': 'こんにちは、',
    'hero.badge': 'バージニア工科大学 (Virginia Tech) 研究員',
    'hero.role': 'バージニア工科大学 CS/ECE 博士課程・大学院研究員',
    'hero.desc': '生体模倣網様体賦活系（RAS）ブレイン・コンピュータ・インターフェース（BCI）、機密GPU上でのLLMサービング性能評価、安全なAIシステムを研究しています。',
    'hero.contact': 'メール',
    'hero.resume': '職歴書 (CV)',
    'section.featured_projects': '主要な研究・プロジェクト',
    'section.featured_projects_desc': '脳波BCIテレパシーおよび機密GPU (NVIDIA H100 CC) LLMサービングの主要成果。',
    'section.recent_posts': '最新の技術記事',
    'section.recent_posts_desc': '生体信号処理、BCI、システム性能プロファイリングに関する技術解説。',
    'section.tech_stack': '技術スタック',
    'section.timeline': '学歴・研究経歴',
    'section.all_projects': 'すべてのプロジェクト →',
    'section.all_posts': 'すべての記事 →',
    'proj.telepathy.title': 'Telepathy: 生体模倣RAS多言語脳波テレパシーBCI',
    'proj.telepathy.desc': '8チャネル非侵襲脳波から言語非依存概念と感情を2.72msで解読（計算量99.7%削減）。',
    'proj.telepathy.cat': 'Research',
    'proj.ispass.title': 'An Empirical Study of LLM Serving in Confidential GPUs (ISPASS 2026 🏆)',
    'proj.ispass.desc': 'ISPASS 2026 Best Paper Honorable Mention: NVIDIA H100 機密GPU環境における vLLM と SGLang の暗号化オーバーヘッド、Chunked Prefill、PagedAttention、推測デコードの実測分析。',
    'proj.ispass.cat': 'Research',
    'post.ras.title': '生体模倣網様体賦活系(RAS)生体信号フィルタリング：BCI計算量99.7%削減の原理',
    'post.ras.desc': '脳幹RASを模倣してアイドリング脳波を遮断し内言語を2.72msで解読するアーキテクチャ解説。',
    'post.prov.title': '信頼できるAIのためのデータ来歴(Data Provenance)の基礎',
    'post.prov.desc': 'データ収集からモデル学習までの全工程を暗号学的に追跡・検証。',
    'post.tee.title': 'コンフィデンシャル・コンピューティングとTEEアーキテクチャ完全ガイド',
    'post.tee.desc': 'Intel SGX、AMD SEV-SNP、ARM CCAアーキテクチャ比較とメモリ暗号化の原理。',
    'post.astro.title': 'Astro と GitHub Pages による無料超高速ポートフォリオ構築',
    'post.astro.desc': 'Astro Content Collections、6言語対応、GitHub Actions 自動デプロイ。',
    'stack.bci': '脳波BCI & 生体神経信号処理',
    'stack.tee': '機密ハードウェア & TEE',
    'stack.ai': '信頼できるAI & LLM',
    'stack.systems': 'システム & クラウドセキュリティ',
    'timeline.phd_title': '博士課程 & 大学院研究員',
    'timeline.phd_org': 'バージニア工科大学 (CS / ECE)',
    'timeline.phd_desc': '生体模倣RAS多言語脳波テレパシーBCIおよび機密GPU環境下でのLLMサービング性能プロファイリング研究。',
    'timeline.bs_title': 'コンピュータ工学士 (B.S.)',
    'timeline.bs_org': 'コンピュータ工学部',
    'timeline.bs_desc': '生体信号処理、OS、計算機アーキテクチャ、暗号学、分散システム、深層学習を修了。',
    'projects.filter_all': 'すべて',
    'projects.filter_research': '研究',
    'projects.filter_ai': 'AI / ML',
    'projects.filter_security': 'セキュリティ',
    'projects.filter_fullstack': 'フルスタック',
    'projects.live_demo': 'デモ',
    'projects.source_code': 'GitHub',
    'projects.paper': '論文 / Citation',
    'projects.slides': 'スライド',
    'blog.filter_all': 'すべて見る',
    'post.reading_time': '分で読めます',
    'post.published': '公開日:',
    'post.toc': '目次',
    'post.back': '← 一覧に戻る',
    'post.comments': 'コメント',
    'post.tags': 'タグ',
    'post.share': '共有',
    'post.translate_notice': '🌐 多言語翻訳で読む:',
    'post.copy_link': '🔗 リンクをコピー',
    'post.copied': '✓ コピー完了！',
    'search.page_title': '全体検索',
    'search.page_desc': '論文、プロジェクト、技術テーマをリアルタイム検索。',
    'search.placeholder': 'キーワードを入力... (Ctrl+K)',
    'search.no_results': '結果が見つかりませんでした。',
    'search.count_prefix': '',
    'search.count_suffix': ' 件の結果',
    'footer.rights': 'All rights reserved.',
    'footer.built_with': 'Astro & GitHub Pages で構築',
  },

  pl: {
    'nav.home': 'Główna',
    'nav.projects': 'Badania i Projekty',
    'nav.blog': 'Blog Techniczny',
    'nav.about': 'O mnie',
    'nav.search': 'Szukaj',
    'hero.greeting': 'Cześć, jestem',
    'hero.badge': 'Badacz akademicki @ Virginia Tech',
    'hero.role': 'Doktorant & Badacz @ Virginia Tech (CS / ECE)',
    'hero.desc': 'Badania nad interfejsami BCI z biomimetycznym RAS, profilowaniem wydajności LLM w poufnych procesorach GPU i bezpiecznymi systemami AI.',
    'hero.contact': 'E-mail',
    'hero.resume': 'Życiorys (CV)',
    'section.featured_projects': 'Wyróżnione Badania i Projekty',
    'section.featured_projects_desc': 'Kluczowe prace nad BCI i obsługą LLM w poufnych GPU (NVIDIA H100 CC).',
    'section.recent_posts': 'Artykuły na Blogu',
    'section.recent_posts_desc': 'Przetwarzanie sygnałów bio, architektura BCI i profilowanie wydajności systemów.',
    'section.tech_stack': 'Technologie',
    'section.timeline': 'Edukacja i Doświadczenie',
    'section.all_projects': 'Wszystkie projekty →',
    'section.all_posts': 'Wszystkie wpisy →',
    'proj.telepathy.title': 'Telepathy: Wielojęzyczne BCI oparte na biomimetycznym RAS',
    'proj.telepathy.desc': 'Dekodowanie pojęć i emocji z 8-kanałowego EEG w 2.72ms przy 99.7% redukcji obliczeń.',
    'proj.telepathy.cat': 'Research',
    'proj.ispass.title': 'An Empirical Study of LLM Serving in Confidential GPUs (ISPASS 2026 🏆)',
    'proj.ispass.desc': 'ISPASS 2026 Best Paper Honorable Mention: Dogłębna analiza wydajności vLLM i SGLang w środowiskach NVIDIA H100 Confidential GPU (Chunked Prefill, PagedAttention, Speculative Decoding).',
    'proj.ispass.cat': 'Research',
    'post.ras.title': 'Biomimetyczne filtrowanie RAS: 99.7% oszczędności mocy w BCI',
    'post.ras.desc': 'Naśladowanie układu siatkowatego (RAS) pnia mózgu do filtrowania bezczynnego EEG i dekodowania w 2.72ms.',
    'post.prov.title': 'Podstawy pochodzenia danych (Data Provenance) dla godnej zaufania AI',
    'post.prov.desc': 'Kryptograficzne śledzenie i weryfikacja cyklu życia danych.',
    'post.tee.title': 'Przewodnik po architekturze poufnego przetwarzania i TEE',
    'post.tee.desc': 'Porównanie Intel SGX, AMD SEV-SNP, ARM CCA i zasad szyfrowania pamięci.',
    'post.astro.title': 'Szybkie portfolio deweloperskie z Astro i GitHub Pages',
    'post.astro.desc': 'Astro Content Collections, obsługa 6 języków i CI/CD z GitHub Actions.',
    'stack.bci': 'Interfejsy BCI i Sygnały Bio',
    'stack.tee': 'Sprzętowe TEE i Poufne Przetwarzanie',
    'stack.ai': 'Bezpieczne AI i Modele LLM',
    'stack.systems': 'Bezpieczeństwo Systemów i Chmury',
    'timeline.phd_title': 'Doktorant i Badacz Akademicki',
    'timeline.phd_org': 'Virginia Tech (CS / ECE)',
    'timeline.phd_desc': 'Badania nad wielojęzycznym BCI RAS oraz profilowaniem wydajności obsługi LLM w poufnych GPU.',
    'timeline.bs_title': 'Inżynier Informatyki (B.S.)',
    'timeline.bs_org': 'Wydział Informatyki',
    'timeline.bs_desc': 'Przetwarzanie sygnałów, systemy operacyjne, kryptografia i deep learning.',
    'projects.filter_all': 'Wszystkie',
    'projects.filter_research': 'Badania',
    'projects.filter_ai': 'AI / ML',
    'projects.filter_security': 'Bezpieczeństwo',
    'projects.filter_fullstack': 'Fullstack',
    'projects.live_demo': 'Demo',
    'projects.source_code': 'GitHub',
    'projects.paper': 'Publikacja / Citation',
    'projects.slides': 'Slajdy',
    'blog.filter_all': 'Wszystkie wpisy',
    'post.reading_time': 'min czytania',
    'post.published': 'Opublikowano:',
    'post.toc': 'Spis treści',
    'post.back': '← Powrót do listy',
    'post.comments': 'Komentarze',
    'post.tags': 'Tagi',
    'post.share': 'Udostępnij',
    'post.translate_notice': '🌐 Natychmiastowe tłumaczenie wielojęzyczne:',
    'post.copy_link': '🔗 Kopiuj link',
    'post.copied': '✓ Skopiowano!',
    'search.page_title': 'Wyszukiwarka',
    'search.page_desc': 'Wyszukiwanie publikacji, projektów i technologii.',
    'search.placeholder': 'Szukaj... (Ctrl+K)',
    'search.no_results': 'Brak wyników.',
    'search.count_prefix': 'Znaleziono: ',
    'search.count_suffix': ' wyników',
    'footer.rights': 'Wszelkie prawa zastrzeżone.',
    'footer.built_with': 'Zbudowano z Astro i GitHub Pages',
  },

  'de-CH': {
    'nav.home': 'Startsiite',
    'nav.projects': 'Forschig & Projekt',
    'nav.blog': 'Tech-Blog',
    'nav.about': 'Über mich',
    'nav.search': 'Sueche',
    'hero.greeting': 'Grüezi, ich bi',
    'hero.badge': 'Doktorand & Forscher @ Virginia Tech',
    'hero.role': 'Doktorand & Forscher @ Virginia Tech (CS / ECE)',
    'hero.desc': 'Forschig im Beriich Biomimetic RAS Brain-Computer Interfaces (BCI), vertraulichs GPU LLM Serving und sicheri AI-System.',
    'hero.contact': 'E-Mail',
    'hero.resume': 'Läbeslauf (CV)',
    'section.featured_projects': 'Wichtigsti Forschigsprojekt',
    'section.featured_projects_desc': 'BCI-Telepathie und LLM-Serving uf vertrauliche GPUs (NVIDIA H100 CC).',
    'section.recent_posts': 'Neusti Tech-Biiträg',
    'section.recent_posts_desc': 'Signalverarbeitig, BCI-Architektur und System-Benchmarking.',
    'section.tech_stack': 'Tech-Stack',
    'section.timeline': 'Uusbildig & Werdegang',
    'section.all_projects': 'Alli Projekt →',
    'section.all_posts': 'Alli Biiträg →',
    'proj.telepathy.title': 'Telepathy: Biomimetischs RAS mehrsprochigs EEG-BCI',
    'proj.telepathy.desc': '8-Kanal EEG wo Sproch-unabhängigi Begriff und Emotion i 2.72ms decodiert (99.7% Reche-Ersparnis).',
    'proj.telepathy.cat': 'Research',
    'proj.ispass.title': 'An Empirical Study of LLM Serving in Confidential GPUs (ISPASS 2026 🏆)',
    'proj.ispass.desc': 'ISPASS 2026 Best Paper Honorable Mention: Systematischi Leistungsanalys vo vLLM und SGLang unter NVIDIA H100 Confidential GPU Umgebige.',
    'proj.ispass.cat': 'Research',
    'post.ras.title': 'Biomimetischi RAS-Filterig: 99.7% Reche-Ersparnis bi Neural BCI',
    'post.ras.desc': 'Wie s retikuläre Aktivierigssystem (RAS) EEG-Leerlauf filteret und Inner-Speech i 2.72ms decodiert.',
    'post.prov.title': 'Grundlage vo Date-Herkunft (Data Provenance) für vertrauenswürdigi AI',
    'post.prov.desc': 'Kryptografischi Nachvollziehbarkeit vom Date-Lebenszyklus.',
    'post.tee.title': 'Iifüehrig i Confidential Computing und TEE-Architektur',
    'post.tee.desc': 'Vergliich vo Intel SGX, AMD SEV-SNP, ARM CCA und Speicherverschlüsselig.',
    'post.astro.title': 'Choschtelosi Entwickler-Siite mit Astro & GitHub Pages',
    'post.astro.desc': 'Astro Content Collections, 6 Sproche und GitHub Actions CI/CD.',
    'stack.bci': 'Neural BCI & Bio-Signalverarbeitig',
    'stack.tee': 'Vertraulichi Hardware & TEE',
    'stack.ai': 'Vertrauenswürdigi AI & LLM',
    'stack.systems': 'System- & Cloud-Sicherheit',
    'timeline.phd_title': 'Doktorand & Forscher',
    'timeline.phd_org': 'Virginia Tech (CS / ECE)',
    'timeline.phd_desc': 'Forschig a mehrsprochigem BCI RAS und Performance-Profiling vo LLM Serving i vertrauliche GPUs.',
    'timeline.bs_title': 'Bachelor i Informatik (B.S.)',
    'timeline.bs_org': 'Informatik-Studium',
    'timeline.bs_desc': 'Signalverarbeitig, Betriebssystem, Kryptographie und Deep Learning.',
    'projects.filter_all': 'Alli',
    'projects.filter_research': 'Forschig',
    'projects.filter_ai': 'AI / ML',
    'projects.filter_security': 'Sicherheit',
    'projects.filter_fullstack': 'Fullstack',
    'projects.live_demo': 'Demo',
    'projects.source_code': 'GitHub',
    'projects.paper': 'Publikation / Citation',
    'projects.slides': 'Foliez',
    'blog.filter_all': 'Alli Biiträg',
    'post.reading_time': 'Min. Leseziit',
    'post.published': 'Veröffentlicht:',
    'post.toc': 'Inhaltsverzeichnis',
    'post.back': '← Zrugg zur Übersicht',
    'post.comments': 'Kommentär',
    'post.tags': 'Tags',
    'post.share': 'Teile',
    'post.translate_notice': '🌐 Sofortigi Übersetzig:',
    'post.copy_link': '🔗 Link kopiere',
    'post.copied': '✓ Kopiert!',
    'search.page_title': 'Suechi',
    'search.page_desc': 'Suech nach Publikatione, Projekt und Skills.',
    'search.placeholder': 'Sueche... (Ctrl+K)',
    'search.no_results': 'Kei Treffer gfunde.',
    'search.count_prefix': 'Gfunde: ',
    'search.count_suffix': ' Treffer',
    'footer.rights': 'Alli Rächt vorbehalte.',
    'footer.built_with': 'Erstellt mit Astro & GitHub Pages',
  },
};
