export type SupportedLanguage = 'ko' | 'en' | 'zh' | 'ja' | 'pl' | 'de-CH';

export interface LanguageOption {
  code: SupportedLanguage;
  label: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'ko', label: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'en', label: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'zh', label: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ja', label: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'pl', label: 'Polish', nativeName: 'Polski', flag: '🇵🇱' },
  { code: 'de-CH', label: 'Swiss German', nativeName: 'Schwiizertüütsch (CH)', flag: '🇨🇭' },
];

export const DEFAULT_LANGUAGE: SupportedLanguage = 'ko';

export const SITE_CONFIG = {
  title: 'Eunseong Park | AI Systems, BCI & Security Researcher',
  name: 'Eunseong Park',
  koreanName: '박은성',
  role: 'Graduate Researcher / Ph.D. Student',
  affiliation: 'Virginia Tech (Department of Computer Science / ECE)',
  description: 'Researching Neural BCI (Biomimetic RAS), Confidential Computing (TEE), Verifiable Data Provenance, and Trustworthy LLM Systems at Virginia Tech.',
  url: 'https://esp-vt.github.io',
  author: 'Eunseong Park',
  email: 'esp@vt.edu',
  phone: '(540) 824-9625',
  social: {
    github: 'https://github.com/esp-vt',
    linkedin: 'https://linkedin.com',
    scholar: 'https://scholar.google.com',
    twitter: 'https://x.com',
  },
  giscus: {
    repo: 'esp-vt/esp-vt.github.io',
    repoId: 'YOUR_REPO_ID',
    category: 'Announcements',
    categoryId: 'YOUR_CATEGORY_ID',
    mapping: 'pathname',
    reactionsEnabled: '1',
    theme: 'preferred_color_scheme',
  },
};

export const UI_TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  ko: {
    // Nav
    'nav.home': '홈',
    'nav.projects': '연구 & 프로젝트',
    'nav.blog': '기술 블로그',
    'nav.about': '소개',
    'nav.search': '검색',

    // Hero
    'hero.greeting': '안녕하세요,',
    'hero.badge': 'Virginia Tech Graduate Researcher',
    'hero.role': 'Virginia Tech 컴퓨터공학 / ECE 대학원 연구원 (Ph.D. Student)',
    'hero.desc': '생체모방 망상활성계(RAS) 기반 뇌파 BCI 텔레파시, 신뢰 실행 환경(TEE), 데이터 프로비넌스 및 안전한 거대 언어 모델(LLM) 시스템을 연구합니다.',
    'hero.view_projects': '연구 & 프로젝트 보기 →',
    'hero.read_blog': '기술 블로그 읽기',
    'hero.resume': '소개 & 이력서 (CV)',

    // Sections
    'section.featured_projects': '대표 연구 및 프로젝트',
    'section.featured_projects_desc': 'Virginia Tech에서 진행 중인 뇌파 기반 신경 텔레파시 BCI, TEE 기밀 머신러닝 및 데이터 프로비넌스 핵심 연구입니다.',
    'section.recent_posts': '최신 기술 포스팅',
    'section.recent_posts_desc': '생체모방 RAS 게이팅, 기밀 컴퓨팅, TEE 아키텍처, 데이터 무결성 및 BCI 보안에 관한 인사이트를 공유합니다.',
    'section.tech_stack': '연구 & 엔지니어링 기술 스택',
    'section.tech_stack_desc': '생체 신경 신호처리, 시스템 보안 및 신뢰 가능한 AI 연구에 활용하는 핵심 기술입니다.',
    'section.timeline': '학력 & 연구 이력',
    'section.timeline_desc': 'Virginia Tech 및 학술/엔지니어링 여정입니다.',
    'section.all_projects': '전체 연구 보기 →',
    'section.all_posts': '전체 글 보기 →',

    // Tech Stacks
    'stack.bci': '뇌파 BCI & 생체 신경 신호처리',
    'stack.tee': '기밀 하드웨어 & TEE',
    'stack.ai': '신뢰 가능한 AI & LLM',
    'stack.systems': '시스템 & 클라우드 보안',

    // Timeline
    'timeline.phd_title': 'Ph.D. 과정 & 대학원 연구원',
    'timeline.phd_org': 'Virginia Tech (CS / ECE)',
    'timeline.phd_desc': '생체모방 망상활성계(RAS) 기반 크로스-링구얼 뇌파 BCI 텔레파시, 하드웨어 앵커 기밀 머신러닝(ConfML-Trust), AMD SEV-SNP/Intel TDX 및 H100 CC 연동 보안 연구 수행.',
    'timeline.bs_title': '컴퓨터공학 학사 (B.S.)',
    'timeline.bs_org': '컴퓨터공학과 학부 과정',
    'timeline.bs_desc': '생체 신호처리, 운영체제(OS), 컴퓨터 구조, 암호학, 분산 시스템, 네트워크 보안 및 딥러닝 알고리즘 이수.',

    // About Page
    'about.page_title': '소개 및 연구자 프로필',
    'about.intro_title': 'Introduction / 소개',
    'about.bio_p1': '안녕하세요! Virginia Tech에서 생체모방 망상활성계(RAS) 기반 뇌파 BCI(Brain-Computer Interface), 신뢰 실행 환경(TEE), 기밀 컴퓨팅(Confidential Computing), 데이터 프로비넌스(Verifiable Data Provenance) 및 안전한 거대 언어 모델(Trustworthy LLMs) 시스템을 연구하고 있는 대학원 연구원 박은성 (Eunseong Park)입니다.',
    'about.bio_p2': '비침습 8채널 EEG 기반의 언어 불변적 개념·감정 해독 텔레파시 엔진(Telepathy)과 AMD SEV-SNP / NVIDIA Hopper H100 CC 기반의 하드웨어 무결성 검증 아키텍처(ConfML-Trust)를 설계하고 있습니다.',
    'about.interests_title': 'Research Interests / 주요 연구 분야',
    'about.interest_bci_title': 'Neural BCI & Biomimetic RAS',
    'about.interest_bci_desc': '생체모방 망상활성계(RAS) 게이팅(99.7% 연산 절감), 속발음(Inner Speech) 개념 해독 및 초저지연(2.72ms) 크로스-링구얼 신경 텔레파시',
    'about.interest_tee_title': 'Confidential Computing & TEE',
    'about.interest_tee_desc': 'AMD SEV-SNP, Intel TDX, Intel SGX, ARM CCA 기반 하드웨어 격리 메모리 및 원격 증명(Remote Attestation)',
    'about.interest_llm_title': 'Trustworthy & Confidential LLMs',
    'about.interest_llm_desc': '비신뢰 LLM 엔지니어링 에이전트 격리, 기밀 LoRA/PEFT 파인튜닝 및 악의적 데이터 오염 방지',
    'about.interest_prov_title': 'Verifiable Data Provenance',
    'about.interest_prov_desc': 'VFS 계층 비우회적 프로비넌스 Shim, Merkle Tree 해시 체이닝 및 하드웨어 서명 Quote 기반 무결성 감사',
    'about.pub_section_title': 'Publications & Research / 주요 논문 및 프로젝트',

    // Projects Page
    'projects.page_title': '전체 연구 & 프로젝트',
    'projects.page_desc': '뇌파 BCI, 신뢰 실행 환경(TEE), 머신러닝 보안, 데이터 프로비넌스 및 시스템 프로젝트입니다.',
    'projects.filter_all': '전체',
    'projects.filter_research': 'Research',
    'projects.filter_ai': 'AI & ML',
    'projects.filter_security': 'Security',
    'projects.filter_fullstack': 'Fullstack',
    'projects.live_demo': '데모 보기',
    'projects.source_code': 'GitHub',
    'projects.paper': '논문 PDF',

    // Blog Page
    'blog.page_title': '기술 블로그',
    'blog.page_desc': '생체 신호처리, BCI, 기밀 컴퓨팅 및 시스템 엔지니어링 과정에서 얻은 인사이트를 공유합니다.',
    'blog.filter_all': '전체 보기',

    // Post Meta
    'post.reading_time': '분 소요',
    'post.published': '작성일:',
    'post.toc': '목차',
    'post.back': '← 목록으로 돌아가기',
    'post.comments': '댓글',
    'post.tags': '태그',
    'post.share': '이 글 공유하기',
    'post.translate_notice': '🌐 언어별 실시간 번역 열람:',
    'post.copy_link': '🔗 링크 복사',
    'post.copied': '✓ 복사 완료!',

    // Search Page
    'search.page_title': '통합 검색',
    'search.page_desc': '블로그 게시글, 프로젝트, 연구 주제를 실시간으로 검색합니다.',
    'search.placeholder': '논문, 프로젝트, 기술 스택, 키워드 검색... (Ctrl+K)',
    'search.no_results': '검색 결과가 없습니다. 다른 검색어를 입력해 보세요.',
    'search.count_prefix': '총 ',
    'search.count_suffix': '개의 결과를 찾았습니다.',
    'search.type_blog': '블로그 글',
    'search.type_project': '프로젝트',

    // Footer
    'footer.rights': 'All rights reserved.',
    'footer.built_with': 'Built with Astro & GitHub Pages',
  },

  en: {
    // Nav
    'nav.home': 'Home',
    'nav.projects': 'Research & Projects',
    'nav.blog': 'Tech Blog',
    'nav.about': 'About',
    'nav.search': 'Search',

    // Hero
    'hero.greeting': 'Hello, I am',
    'hero.badge': 'Virginia Tech Graduate Researcher',
    'hero.role': 'Graduate Researcher / Ph.D. Student @ Virginia Tech (CS / ECE)',
    'hero.desc': 'Researching Biomimetic RAS Neural BCI Telepathy, Trusted Execution Environments (TEE), Verifiable Data Provenance, and Trustworthy LLM Systems at Virginia Tech.',
    'hero.view_projects': 'View Research & Projects →',
    'hero.read_blog': 'Read Tech Blog',
    'hero.resume': 'About & Resume (CV)',

    // Sections
    'section.featured_projects': 'Featured Research & Projects',
    'section.featured_projects_desc': 'Core research on EEG-based Neural BCI telepathy, TEE confidential ML, and data provenance verification at Virginia Tech.',
    'section.recent_posts': 'Recent Technical Articles',
    'section.recent_posts_desc': 'Deep-dives into biomimetic RAS filtering, confidential computing, TEE architectures, and neural BCI security.',
    'section.tech_stack': 'Research & Engineering Stack',
    'section.tech_stack_desc': 'Core technologies utilized for bio-signal processing, systems security, and trustworthy AI research.',
    'section.timeline': 'Education & Experience',
    'section.timeline_desc': 'Academic and engineering trajectory at Virginia Tech and beyond.',
    'section.all_projects': 'All Research & Projects →',
    'section.all_posts': 'All Articles →',

    // Tech Stacks
    'stack.bci': 'Neural BCI & Bio-Signal Processing',
    'stack.tee': 'Confidential Hardware & TEE',
    'stack.ai': 'Trustworthy AI & LLM',
    'stack.systems': 'Systems & Cloud Security',

    // Timeline
    'timeline.phd_title': 'Ph.D. Student & Graduate Researcher',
    'timeline.phd_org': 'Virginia Tech (CS / ECE)',
    'timeline.phd_desc': 'Conducting research on biomimetic RAS-gated cross-lingual neural BCI telepathy, hardware-anchored confidential machine learning (ConfML-Trust), and secure LLM fine-tuning on AMD SEV-SNP / H100 CC.',
    'timeline.bs_title': 'B.S. in Computer Science & Engineering',
    'timeline.bs_org': 'Undergraduate CS Program',
    'timeline.bs_desc': 'Completed coursework in Bio-signal Processing, Operating Systems, Computer Architecture, Cryptography, Distributed Systems, Network Security, and Deep Learning algorithms.',

    // About Page
    'about.page_title': 'About & Researcher Profile',
    'about.intro_title': 'Introduction',
    'about.bio_p1': 'Hello! I am Eunseong Park, a Graduate Researcher and Ph.D. Student at Virginia Tech studying Biomimetic RAS Neural BCI, Trusted Execution Environments (TEE), Confidential Computing, Verifiable Data Provenance, and Trustworthy Large Language Models (LLMs).',
    'about.bio_p2': 'I design Telepathy (language-agnostic 8-channel EEG BCI engine with 99.7% compute savings and 2.72ms latency) and ConfML-Trust (hardware-anchored confidential ML with immutable data lineage across untrusted cloud workflows).',
    'about.interests_title': 'Research Interests',
    'about.interest_bci_title': 'Neural BCI & Biomimetic RAS',
    'about.interest_bci_desc': 'Biomimetic Reticular Activating System (RAS) gating (99.7% compute saved), inner speech concept decoding, and 2.72ms cross-lingual neural telepathy.',
    'about.interest_tee_title': 'Confidential Computing & TEE',
    'about.interest_tee_desc': 'Hardware-isolated memory encryption and Remote Attestation via AMD SEV-SNP, Intel TDX, Intel SGX, and ARM CCA.',
    'about.interest_llm_title': 'Trustworthy & Confidential LLMs',
    'about.interest_llm_desc': 'Untrusted ML engineering isolation, confidential LoRA/PEFT fine-tuning, and robust defense against data poisoning.',
    'about.interest_prov_title': 'Verifiable Data Provenance',
    'about.interest_prov_desc': 'Non-bypassable VFS measurement shims, streaming Merkle commitment trees, and hardware quote verification.',
    'about.pub_section_title': 'Publications & Research Projects',

    // Projects Page
    'projects.page_title': 'All Research & Projects',
    'projects.page_desc': 'Neural BCI telepathy, hardware-isolated TEE, ML security, verifiable provenance, and systems engineering projects.',
    'projects.filter_all': 'All',
    'projects.filter_research': 'Research',
    'projects.filter_ai': 'AI & ML',
    'projects.filter_security': 'Security',
    'projects.filter_fullstack': 'Fullstack',
    'projects.live_demo': 'Live Demo',
    'projects.source_code': 'GitHub',
    'projects.paper': 'Paper PDF',

    // Blog Page
    'blog.page_title': 'Technical Blog',
    'blog.page_desc': 'Technical insights, system design records, and research findings in neural BCI and AI security.',
    'blog.filter_all': 'All Posts',

    // Post Meta
    'post.reading_time': 'min read',
    'post.published': 'Published:',
    'post.toc': 'Table of Contents',
    'post.back': '← Back to List',
    'post.comments': 'Comments',
    'post.tags': 'Tags',
    'post.share': 'Share Article',
    'post.translate_notice': '🌐 Instant Multi-Language Translation:',
    'post.copy_link': '🔗 Copy Link',
    'post.copied': '✓ Copied!',

    // Search Page
    'search.page_title': 'Global Search',
    'search.page_desc': 'Real-time search across blog posts, research projects, and technical topics.',
    'search.placeholder': 'Search papers, projects, skills, topics... (Ctrl+K)',
    'search.no_results': 'No matching results found. Try another query.',
    'search.count_prefix': 'Found ',
    'search.count_suffix': ' results.',
    'search.type_blog': 'Blog Post',
    'search.type_project': 'Project',

    // Footer
    'footer.rights': 'All rights reserved.',
    'footer.built_with': 'Built with Astro & GitHub Pages',
  },

  zh: {
    'nav.home': '首页',
    'nav.projects': '研究与项目',
    'nav.blog': '技术博客',
    'nav.about': '关于我',
    'nav.search': '搜索',
    'hero.greeting': '你好，我是',
    'hero.badge': '弗吉尼亚理工大学 (Virginia Tech) 研究员',
    'hero.role': '弗吉尼亚理工大学 计算机/ECE 博士生 & 研究员',
    'hero.desc': '专注于生体仿生网状激活系统（RAS）脑机接口（BCI）、可信执行环境（TEE）、数据溯源及安全大语言模型（LLM）系统研究。',
    'hero.view_projects': '查看研究与项目 →',
    'hero.read_blog': '阅读技术博客',
    'hero.resume': '个人介绍 & 简历 (CV)',
    'section.featured_projects': '重点研究与项目',
    'section.featured_projects_desc': '关于脑电波神经传心BCI、基于硬件TEE的机密机器学习与数据血缘验证核心成果。',
    'section.recent_posts': '最新技术文章',
    'section.recent_posts_desc': '关于生体仿生RAS过滤、机密计算、TEE架构、数据完整性及BCI安全的深度解析。',
    'section.tech_stack': '研究与工程技术栈',
    'section.tech_stack_desc': '用于生体神经信号处理、系统安全与可信AI研究的核心技术。',
    'section.timeline': '教育与学术经历',
    'section.timeline_desc': '弗吉尼亚理工大学及学术工程历程。',
    'section.all_projects': '查看所有研究 →',
    'section.all_posts': '查看全部文章 →',
    'stack.bci': '脑机接口(BCI)与神经信号处理',
    'stack.tee': '机密硬件与TEE',
    'stack.ai': '可信AI与大语言模型',
    'stack.systems': '系统与云安全',
    'timeline.phd_title': '博士研究生 & 大学院研究员',
    'timeline.phd_org': '弗吉尼亚理工大学 (CS / ECE)',
    'timeline.phd_desc': '开展生体仿生RAS多语言脑波传心BCI、硬件锚点机密机器学习（ConfML-Trust）及安全LLM微调研究。',
    'timeline.bs_title': '计算机工程学士 (B.S.)',
    'timeline.bs_org': '计算机工程专业',
    'timeline.bs_desc': '完成脑电信号处理、操作系统、计算机体系结构、密码学及深度学习课程。',
    'about.page_title': '关于我与研究者履历',
    'about.intro_title': '个人简介',
    'about.bio_p1': '你好！我是朴恩成 (Eunseong Park)，弗吉尼亚理工大学博士研究生，主要研究脑机接口(BCI)、生体仿生RAS过滤、可信执行环境 (TEE) 和安全大模型系统。',
    'about.bio_p2': '主导研发 Telepathy（8通道EEG无语种限制传心引擎，算力节约99.7%，超低延迟2.72ms）与 ConfML-Trust 硬件安全体系。',
    'about.interests_title': '主要研究方向',
    'about.interest_bci_title': '脑机接口(BCI)与生体仿生RAS',
    'about.interest_bci_desc': '生体仿生网状激活系统(RAS)门控（算力降低99.7%）、心语概念解算与2.72ms跨语言神经传心。',
    'about.interest_tee_title': '机密计算与TEE硬件隔离',
    'about.interest_tee_desc': '基于 AMD SEV-SNP、Intel TDX、Intel SGX、ARM CCA 的内存加密与远程证明。',
    'about.interest_llm_title': '安全可信大语言模型',
    'about.interest_llm_desc': '不可信 LLM 智能体隔离、机密 LoRA/PEFT 训练与数据投毒防护。',
    'about.interest_prov_title': '可验证数据溯源体系',
    'about.interest_prov_desc': 'VFS 层非旁路度量 Shim、Merkle 承诺树流式哈希与硬件签名 Quote 验证。',
    'about.pub_section_title': '学术论文与研究成果',
    'projects.page_title': '全部研究与项目',
    'projects.page_desc': '脑机接口、硬件隔离TEE、机器学习安全、数据溯源及系统工程项目展示。',
    'projects.filter_all': '全部',
    'projects.filter_research': '研究论文',
    'projects.filter_ai': '人工智能与ML',
    'projects.filter_security': '系统安全',
    'projects.filter_fullstack': '全栈工程',
    'projects.live_demo': '演示链接',
    'projects.source_code': 'GitHub 源码',
    'projects.paper': '论文 PDF',
    'blog.page_title': '技术博客',
    'blog.page_desc': '分享神经信号处理、BCI、系统安全与机器学习领域的工程实践与思考。',
    'blog.filter_all': '查看全部',
    'post.reading_time': '分钟阅读',
    'post.published': '发布日期：',
    'post.toc': '目录导航',
    'post.back': '← 返回列表',
    'post.comments': '讨论区',
    'post.tags': '标签',
    'post.share': '分享文章',
    'post.translate_notice': '🌐 实时多语言翻译阅读：',
    'post.copy_link': '🔗 复制链接',
    'post.copied': '✓ 已复制！',
    'search.page_title': '全局检索',
    'search.page_desc': '实时检索文章、项目、技术栈与研究主题。',
    'search.placeholder': '搜索论文、项目、技术栈、关键词... (Ctrl+K)',
    'search.no_results': '未找到匹配结果，请尝试其他关键词。',
    'search.count_prefix': '共检索到 ',
    'search.count_suffix': ' 条结果。',
    'search.type_blog': '博客文章',
    'search.type_project': '项目成果',
    'footer.rights': '保留所有权利。',
    'footer.built_with': '基于 Astro 与 GitHub Pages 构建',
  },

  ja: {
    'nav.home': 'ホーム',
    'nav.projects': '研究・プロジェクト',
    'nav.blog': '技術ブログ',
    'nav.about': '自己紹介',
    'nav.search': '検索',
    'hero.greeting': 'こんにちは、',
    'hero.badge': 'バージニア工科大学 (Virginia Tech) 大学院研究員',
    'hero.role': 'バージニア工科大学 CS/ECE 博士課程・大学院研究員',
    'hero.desc': '生体模倣網様体賦活系（RAS）ブレイン・コンピュータ・インターフェース（BCI）、信頼できる実行環境（TEE）、データ来歴、安全なLLMシステムの研究を行っています。',
    'hero.view_projects': '研究とプロジェクトを見る →',
    'hero.read_blog': '技術ブログを読む',
    'hero.resume': '自己紹介と職歴 (CV)',
    'section.featured_projects': '代表的な研究・プロジェクト',
    'section.featured_projects_desc': '脳波ベースの神経テレパシーBCI、TEE機密機械学習およびデータ来歴検証の主要研究。',
    'section.recent_posts': '最新の技術記事',
    'section.recent_posts_desc': '生体模倣RASフィルタリング、機密コンピューティング、TEEアーキテクチャ、BCI安全技術に関する解説。',
    'section.tech_stack': '研究・技術スタック',
    'section.tech_stack_desc': '生体神経信号処理、システムセキュリティと信頼できるAI研究に活用しているコア技術群。',
    'section.timeline': '学歴・研究経歴',
    'section.timeline_desc': 'バージニア工科大学およびこれまでの学術・開発の歩み。',
    'section.all_projects': 'すべての研究を見る →',
    'section.all_posts': 'すべての記事を見る →',
    'stack.bci': '脳波BCI & 生体神経信号処理',
    'stack.tee': '機密ハードウェア & TEE',
    'stack.ai': '信頼できるAI & LLM',
    'stack.systems': 'システム & クラウドセキュリティ',
    'timeline.phd_title': '博士課程 & 大学院研究員',
    'timeline.phd_org': 'バージニア工科大学 (CS / ECE)',
    'timeline.phd_desc': '生体模倣RAS多言語脳波テレパシーBCI、ハードウェアアンカー機密機械学習(ConfML-Trust)および安全なLLMファインチューニング研究。',
    'timeline.bs_title': 'コンピュータ工学士 (B.S.)',
    'timeline.bs_org': 'コンピュータ工学部',
    'timeline.bs_desc': '生体信号処理、OS、計算機アーキテクチャ、暗号学、分散システム、ディープラーニングを修了。',
    'about.page_title': 'プロフィールと研究業績',
    'about.intro_title': '自己紹介',
    'about.bio_p1': 'こんにちは！バージニア工科大学 (Virginia Tech) で生体模倣RASブレイン・コンピュータ・インターフェース (BCI)、信頼できる実行環境 (TEE)、データ来歴保証 (Data Provenance) を研究している博士課程のパク・ウンソン (Eunseong Park) です。',
    'about.bio_p2': '非侵襲8チャネル脳波による言語非依存概念解読エンジン（Telepathy：演算99.7%削減、遅延2.72ms）とConfML-Trustを設計しています。',
    'about.interests_title': '主な研究分野',
    'about.interest_bci_title': '神経BCI & 生体模倣RAS',
    'about.interest_bci_desc': '生体模倣網様体賦活系(RAS)ゲーティング(演算99.7%削減)、内言語概念解読および2.72ms超低遅延多言語神経テレパシー。',
    'about.interest_tee_title': 'コンフィデンシャル・コンピューティング & TEE',
    'about.interest_tee_desc': 'AMD SEV-SNP、Intel TDX、Intel SGX、ARM CCA を用いたメモリ暗号化とリモート認証。',
    'about.interest_llm_title': '安全で信頼できる LLM システム',
    'about.interest_llm_desc': '非信頼 LLM エージェントの隔離、機密 LoRA/PEFT ファインチューニングとデータ汚染防止。',
    'about.interest_prov_title': '検証可能なデータ来歴保証',
    'about.interest_prov_desc': 'VFS 層の非バイパス計測 Shim、Merkle Tree コミットメントとハードウェア署名 Quote 監査。',
    'about.pub_section_title': '主要論文・発表',
    'projects.page_title': 'すべての研究とプロジェクト',
    'projects.page_desc': '脳波BCIテレパシー、ハードウェアTEE、機械学習セキュリティ、データ来歴検証。',
    'projects.filter_all': 'すべて',
    'projects.filter_research': '研究',
    'projects.filter_ai': 'AI / ML',
    'projects.filter_security': 'セキュリティ',
    'projects.filter_fullstack': 'フルスタック',
    'projects.live_demo': 'デモを見る',
    'projects.source_code': 'GitHub',
    'projects.paper': '論文 PDF',
    'blog.page_title': '技術ブログ',
    'blog.page_desc': '生体信号処理、BCI、AIセキュリティとシステムアーキテクチャの研究知見を発信します。',
    'blog.filter_all': 'すべて見る',
    'post.reading_time': '分で読めます',
    'post.published': '公開日:',
    'post.toc': '目次',
    'post.back': '← 一覧に戻る',
    'post.comments': 'コメント',
    'post.tags': 'タグ',
    'post.share': '記事を共有',
    'post.translate_notice': '🌐 リアルタイム多言語翻訳で読む:',
    'post.copy_link': '🔗 リンクをコピー',
    'post.copied': '✓ コピー完了！',
    'search.page_title': '全体検索',
    'search.page_desc': '記事、プロジェクト、研究テーマをリアルタイム検索します。',
    'search.placeholder': '論文、プロジェクト、技術スタック、キーワードを検索... (Ctrl+K)',
    'search.no_results': '該当する結果がありませんでした。',
    'search.count_prefix': '',
    'search.count_suffix': ' 件の結果が見つかりました。',
    'search.type_blog': 'ブログ記事',
    'search.type_project': 'プロジェクト',
    'footer.rights': 'All rights reserved.',
    'footer.built_with': 'Astro & GitHub Pages で構築',
  },

  pl: {
    'nav.home': 'Główna',
    'nav.projects': 'Badania i Projekty',
    'nav.blog': 'Blog Techniczny',
    'nav.about': 'O mnie',
    'nav.search': 'Szukaj',
    'hero.greeting': 'Cześć, jestem',
    'hero.badge': 'Badacz akademicki @ Virginia Tech',
    'hero.role': 'Doktorant & Badacz akademicki @ Virginia Tech (CS / ECE)',
    'hero.desc': 'Badania nad biomimetycznymi interfejsami mózg-komputer (BCI RAS), zaufanymi środowiskami wykonawczymi (TEE), weryfikowalnym pochodzeniem danych i bezpiecznymi modelami LLM w Virginia Tech.',
    'hero.view_projects': 'Zobacz badania i projekty →',
    'hero.read_blog': 'Czytaj blog techniczny',
    'hero.resume': 'O mnie i CV',
    'section.featured_projects': 'Wyróżnione Badania i Projekty',
    'section.featured_projects_desc': 'Kluczowe prace nad telepatią mózgową BCI, poufnym uczeniem maszynowym TEE i integralnością danych.',
    'section.recent_posts': 'Najnowsze Artykuły Techniczne',
    'section.recent_posts_desc': 'Analizy biomimetycznego filtrowania RAS, poufnego przetwarzania, architektury TEE i bezpieczeństwa BCI.',
    'section.tech_stack': 'Stos Technologiczny i Badawczy',
    'section.tech_stack_desc': 'Kluczowe technologie wykorzystywane w przetwarzaniu sygnałów bio, bezpieczeństwie systemów i AI.',
    'section.timeline': 'Edukacja i Doświadczenie',
    'section.timeline_desc': 'Ścieżka akademicka i inżynieryjna w Virginia Tech.',
    'section.all_projects': 'Wszystkie projekty →',
    'section.all_posts': 'Wszystkie wpisy →',
    'stack.bci': 'Interfejsy Mózg-Komputer (BCI) i Sygnały Bio',
    'stack.tee': 'Sprzętowe TEE i Poufne Przetwarzanie',
    'stack.ai': 'Bezpieczne AI i Modele LLM',
    'stack.systems': 'Bezpieczeństwo Systemów i Chmury',
    'timeline.phd_title': 'Doktorant i Badacz Akademicki',
    'timeline.phd_org': 'Virginia Tech (CS / ECE)',
    'timeline.phd_desc': 'Badania nad telepatią BCI opartą na biomimetycznym RAS, poufnym uczeniem maszynowym (ConfML-Trust) i bezpiecznym dostrajaniem LLM.',
    'timeline.bs_title': 'Inżynier Informatyki (B.S.)',
    'timeline.bs_org': 'Wydział Informatyki',
    'timeline.bs_desc': 'Ukończone kursy z przetwarzania sygnałów, systemów operacyjnych, architektury komputerów, kryptografii i deep learningu.',
    'about.page_title': 'O mnie i Profil Badacza',
    'about.intro_title': 'Wprowadzenie',
    'about.bio_p1': 'Cześć! Nazywam się Eunseong Park, jestem doktorantem w Virginia Tech, zajmującym się interfejsami mózg-komputer (BCI RAS), zaufanymi środowiskami wykonawczymi (TEE) oraz bezpieczeństwem modeli LLM.',
    'about.bio_p2': 'Projektuję silnik Telepathy (8-kanałowy BCI z 99.7% oszczędnością obliczeń i opóźnieniem 2.72ms) oraz architekturę ConfML-Trust.',
    'about.interests_title': 'Główne Obszary Badawcze',
    'about.interest_bci_title': 'Interfejsy BCI i Biomimetyczny RAS',
    'about.interest_bci_desc': 'Bramkowanie RAS (oszczędność 99.7% mocy), dekodowanie mowy wewnętrznej i wielojęzyczna telepatia 2.72ms.',
    'about.interest_tee_title': 'Poufne Przetwarzanie i TEE',
    'about.interest_tee_desc': 'Sprzętowo izolowana pamięć i zdalna atestacja na AMD SEV-SNP, Intel TDX, Intel SGX i ARM CCA.',
    'about.interest_llm_title': 'Bezpieczne i Zaufane Modele LLM',
    'about.interest_llm_desc': 'Izolacja niezaufanych agentów ML, poufne dostrajanie LoRA/PEFT i ochrona przed zatruwaniem danych.',
    'about.interest_prov_title': 'Weryfikowalne Pochodzenie Danych',
    'about.interest_prov_desc': 'Nieomijalne shimy pomiarowe VFS, drzewa Merkle i audyt oparty na podpisach sprzętowych.',
    'about.pub_section_title': 'Publikacje i Projekty Naukowe',
    'projects.page_title': 'Wszystkie Badania i Projekty',
    'projects.page_desc': 'Telepatia BCI, izolowane sprzętowo TEE, bezpieczeństwo ML i integralność danych.',
    'projects.filter_all': 'Wszystkie',
    'projects.filter_research': 'Badania',
    'projects.filter_ai': 'AI / ML',
    'projects.filter_security': 'Bezpieczeństwo',
    'projects.filter_fullstack': 'Fullstack',
    'projects.live_demo': 'Demo online',
    'projects.source_code': 'GitHub',
    'projects.paper': 'PDF Publikacji',
    'blog.page_title': 'Blog Techniczny',
    'blog.page_desc': 'Praktyczne wnioski z zakresu przetwarzania sygnałów EEG, BCI i bezpieczeństwa AI.',
    'blog.filter_all': 'Wszystkie wpisy',
    'post.reading_time': 'min czytania',
    'post.published': 'Opublikowano:',
    'post.toc': 'Spis treści',
    'post.back': '← Powrót do listy',
    'post.comments': 'Komentarze',
    'post.tags': 'Tagi',
    'post.share': 'Udostępnij artykuł',
    'post.translate_notice': '🌐 Natychmiastowe tłumaczenie wielojęzyczne:',
    'post.copy_link': '🔗 Kopiuj link',
    'post.copied': '✓ Skopiowano!',
    'search.page_title': 'Wyszukiwarka',
    'search.page_desc': 'Wyszukiwanie wpisów, projektów i technologii w czasie rzeczywistym.',
    'search.placeholder': 'Szukaj publikacji, projektów, umiejętności... (Ctrl+K)',
    'search.no_results': 'Brak wyników.',
    'search.count_prefix': 'Znaleziono: ',
    'search.count_suffix': ' wyników.',
    'search.type_blog': 'Wpis na blogu',
    'search.type_project': 'Projekt',
    'footer.rights': 'Wszelkie prawa zastrzeżone.',
    'footer.built_with': 'Zbudowano z Astro i GitHub Pages',
  },

  'de-CH': {
    'nav.home': 'Startsiite',
    'nav.projects': 'Forschig & Projekt',
    'nav.blog': 'Tech-Blog',
    'nav.about': 'Über mich',
    'nav.search': 'Sueche',
    'hero.greeting': 'Grüezi, ich bi',
    'hero.badge': 'Doktorand & Forscher @ Virginia Tech',
    'hero.role': 'Doktorand & Forscher @ Virginia Tech (CS / ECE)',
    'hero.desc': 'Forschig im Beriich Biomimetic RAS Brain-Computer Interfaces (BCI), Trusted Execution Environments (TEE), Verifiable Data Provenance und sicheri LLM-System.',
    'hero.view_projects': 'Forschig & Projekt aaluege →',
    'hero.read_blog': 'Tech-Blog läse',
    'hero.resume': 'Über mich & Läbeslauf (CV)',
    'section.featured_projects': 'Wichtigsti Forschigsprojekt',
    'section.featured_projects_desc': 'Aktuelli Durchbrüch i EEG-basierter BCI-Telepathie, vertraulichem Machine Learning und Herkunftssicherig vo Date.',
    'section.recent_posts': 'Neusti Technischi Artikel',
    'section.recent_posts_desc': 'Tüüfi Iiblick i biomimetischi RAS-Filter, vertraulichs Reche, TEE-Architektur und BCI-Sicherheit.',
    'section.tech_stack': 'Forschigs- & Tech-Stack',
    'section.tech_stack_desc': 'Kerntechnologie für Bio-Signalverarbeitig, Systemsicherheit und vertrauenswürdigi AI.',
    'section.timeline': 'Uusbildig & Werdegang',
    'section.timeline_desc': 'Akademischi und technischi Statione a de Virginia Tech.',
    'section.all_projects': 'Alli Projekt aaluege →',
    'section.all_posts': 'Alli Biiträg aaluege →',
    'stack.bci': 'Neural BCI & Bio-Signalverarbeitig',
    'stack.tee': 'Vertraulichi Hardware & TEE',
    'stack.ai': 'Vertrauenswürdigi AI & LLM',
    'stack.systems': 'System- & Cloud-Sicherheit',
    'timeline.phd_title': 'Doktorand & Akademische Forscher',
    'timeline.phd_org': 'Virginia Tech (CS / ECE)',
    'timeline.phd_desc': 'Forschig a biomimetischem RAS BCI, hardware-gsicheretem vertraulichem Machine Learning (ConfML-Trust) und sichers LLM-Finetuning.',
    'timeline.bs_title': 'Bachelor i Informatik (B.S.)',
    'timeline.bs_org': 'Informatik-Studium',
    'timeline.bs_desc': 'Signalverarbeitig, Betriebssystem, Rechnerarchitektur, Kryptographie und Deep Learning abgschlosse.',
    'about.page_title': 'Über mich & Forscher-Profil',
    'about.intro_title': 'Iifüehrig',
    'about.bio_p1': 'Grüezi! Ich bi de Eunseong Park, Doktorand a de Virginia Tech. Mini Schwerpünkt sind Brain-Computer Interfaces (BCI), biomimetischi RAS-Filterig, TEEs und sicheri LLMs.',
    'about.bio_p2': 'Ich entwickle Telepathy (8-Kanal EEG Telepathie-Engine mit 99.7% Reche-Ersparnis und 2.72ms Latenz) sowie d ConfML-Trust Architektur.',
    'about.interests_title': 'Haupt-Forschigsgebiet',
    'about.interest_bci_title': 'Neural BCI & Biomimetischs RAS',
    'about.interest_bci_desc': 'Biomimetischs RAS-Gating (99.7% Energie-Ersparnis), Inner-Speech-Decodierig und 2.72ms mehrsprochigi Telepathie.',
    'about.interest_tee_title': 'Confidential Computing & TEE',
    'about.interest_tee_desc': 'Hardware-isolierti Speicherverschlüsselig und Remote Attestation mit AMD SEV-SNP, Intel TDX, Intel SGX und ARM CCA.',
    'about.interest_llm_title': 'Sicheri & Vertrauenswürdigi LLMs',
    'about.interest_llm_desc': 'Isolierig vo unsichere LLM-Agente, vertraulichs LoRA/PEFT Finetuning und Schutz vor Date-Vergiftig.',
    'about.interest_prov_title': 'Verifizierbari Date-Herkunft (Provenance)',
    'about.interest_prov_desc': 'VFS-Mäss-Shims, Merkle-Commitment-Bäum und hardware-signierti Quotes für Audits.',
    'about.pub_section_title': 'Publikatione & Forschigsergebnis',
    'projects.page_title': 'Alli Forschigsprojekt',
    'projects.page_desc': 'BCI-Telepathie, hardware-isolierti TEEs, ML-Sicherheit und Herkunftssicherig.',
    'projects.filter_all': 'Alli',
    'projects.filter_research': 'Forschig',
    'projects.filter_ai': 'AI / ML',
    'projects.filter_security': 'Sicherheit',
    'projects.filter_fullstack': 'Fullstack',
    'projects.live_demo': 'Live-Demo',
    'projects.source_code': 'GitHub',
    'projects.paper': 'Paper PDF',
    'blog.page_title': 'Tech-Blog',
    'blog.page_desc': 'Erfahrige und Forschigsnotize über EEG-Signalverarbeitig, BCI und AI-Security.',
    'blog.filter_all': 'Alli Biiträg',
    'post.reading_time': 'Min. Leseziit',
    'post.published': 'Veröffentlicht:',
    'post.toc': 'Inhaltsverzeichnis',
    'post.back': '← Zrugg zur Übersicht',
    'post.comments': 'Kommentär',
    'post.tags': 'Tags',
    'post.share': 'Biitrag teile',
    'post.translate_notice': '🌐 Sofortigi Übersetzig i anderi Sproche:',
    'post.copy_link': '🔗 Link kopiere',
    'post.copied': '✓ Kopiert!',
    'search.page_title': 'Gsamti Suechi',
    'search.page_desc': 'Suech i Echtziit nach Blog-Biiträg, Forschigsprojekt und Skills.',
    'search.placeholder': 'Publikatione, Projekt, Skills sueche... (Ctrl+K)',
    'search.no_results': 'Kei Treffer gfunde.',
    'search.count_prefix': 'Gfunde: ',
    'search.count_suffix': ' Treffer.',
    'search.type_blog': 'Blog-Biitrag',
    'search.type_project': 'Projekt',
    'footer.rights': 'Alli Rächt vorbehalte.',
    'footer.built_with': 'Erstellt mit Astro & GitHub Pages',
  },
};
